- Doolda/Doolda/Data/Repositories/UserRepository.swift
- Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift
- Doolda/Doolda/Presentation/ViewModels/PairingViewModel.swift
- Doolda/Doolda/UI/ViewControllers/PairingViewController.swift
* 연결하기 버튼 하단에 혼자 쓰러가기 버튼을 추가했습니다
* 혼자 사용하는 유저는 pairId를 자신의 id로 갖게 됩니다. 추후에 다이어리 페이지 작성하기 버튼을 만들때, pairId와 자신의 id가 같은지의 여부로 이 유저가 혼자 사용자는 유저인지, 다른 유저와 함께 사용하는지를 판별할 수 있습니다.
* 기존 pairingViewController에 코딩 컨벤션과 맞지 않은 부분이 있어, 리팩토링까지 진행했습니다.
| 라이트 모드 | 다크 모드 |
| ---- | ---- |
| <img width="307" alt="스크린샷 2021-11-14 오후 4 21 57" src="https://user-images.githubusercontent.com/61934702/141671499-cc994ba6-e052-4a2a-9919-030d21204c16.png"> | <img width="307" alt="스크린샷 2021-11-14 오후 4 22 19" src="https://user-images.githubusercontent.com/61934702/141671524-1a1c4632-2e84-43af-b47a-ac1fc1a3d565.png"> |
> 혼자 사용할 수 있도록 수정

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/Data/DataTransferObjects/PageDocument.swift
- Doolda/Doolda/Data/Interfaces/URLSessionNetworkServiceProtocol.swift
- Doolda/Doolda/Data/Repositories/PageRepository.swift
- Doolda/Doolda/Service/Networks/URLSessionNetworkService.swift
- Doolda/Doolda/Support/Constants/API.swift
- Doolda/Doolda/Support/Extensions/DateFormatter+Extensions.swift
- Doolda/Doolda/UI/Coordinators/EditPageViewCoordinator.swift
* 아.. 진짜 엔티티 + Firebase 최악이네요 ㅋㅋ
* Firestore 에서 데이터 query해오는거에서 엄청나게 삽질했습니다 (코딩도 못하고 계속 문서찾아보고 검색하고...)
* 결국에 해내긴했는데 코드가 지저분하고 맘에안드네요. No SQL은 여러모로 Swift Codable이랑 잘 안맞는다고 느껴져요. 괜히 구글이 SDK를 권장(?) 하는게 아닌듯..
* DB에 page 콜렉션에 `{pairId}+{jsonPath}` 라는 이름으로 `PageEntity`가 올라가게 구현했습니다.
> PageRepository 기능 구현, PageDocument 정의, 추가적으로 필요한 Firestore API 구현

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/Domain/Entities/StickerComponentEntity.swift
- Doolda/Doolda/Domain/Entities/StickerPackEntity.swift
- Doolda/Doolda/Domain/UseCases/StickerUseCase.swift
- Doolda/Doolda/Presentation/ViewModels/StickerPickerViewModel.swift
* 이부분 고민할 사항이 많은데 약간 가볍게 넘어간 것 같긴해요. 일단 제가 생긱하기로 가장 자연스러운 방법으로 코드를 짰는데 확인 한번만 부탁드립니다!
~~1. StickerPackEntity 안에 스티커를 불러올 수 있는 값
이부분에서 2가지 선택지가 있는데 stickerComponenetEntity의 배열을 통쨰로 가지게 하는 법과, 그걸 참조하는 url만 가지게 하는 방식이 있다고 생각했습니다. 첫번째는 개인적인 생각으로 entity한테 너무 많은 역할을 주는 것 같아서 (stickerComponenetEntity 정의하기 위해선 ㄴscale, frame 등을 알아야하기 때문에) 후자의 방향으로 갔습니다.
그래서 제가 생각한 방식은 이렇습니다
VC에서 탭으로 선택함 -> 그 선택한 indexPath로 VM의 배열에서 URL을 찾음 -> 그 URL을 찾아 componenetEntity를 생성하고 VC한테 다시 보냄 -> VC그걸 받아서 delegate로 전달~~
* UseCase에서 static엔티티를 가지고 있고 VC에서 선택한 indexpath에 따라 StickerComponentEntity를 넘겨주는 식으로 변경했습니다
혹시 제가 잘못 이해한 부분이 있다면 고쳐주시면 감사하겠습니다!
> sticker관련 Presentation, Domain 단 구현

- .gitignore
- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/Resources/Info.plist
- Doolda/Doolda/Support/Constants/API.swift
- Doolda/Doolda/Support/Constants/Secrets.swift
* 해봤는데 아주아주아주아주잘돼요. 이제 협의하고 사용하는쪽만 고려해주면 될 듯 합니다.
* API Key 관련해서는 `.xcconfig` 파일에 담아두고 `Secrets` 에 `static let` 으로 선언해두고 쓰는방식이 좋을 것 같아서 그렇게했는데 어떤지 알려주세요. 참고로 `.xcconfig` 는 `.gitignore` 에 추가했으니 slack을 통해서 공유할게요
> FirebaseCloudMessaging API 추가

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
- Doolda/Doolda/Domain/Entities/DooldaInfoType.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/SettingsScene/SettingsDetailedInfoViewController.swift
- Doolda/Doolda/SettingsScene/SettingsOptionViewController.swift
- Doolda/Doolda/SettingsScene/SettingsTableViewCell.swift
- Doolda/Doolda/SettingsScene/SettingsTableViewHeader.swift
- Doolda/Doolda/SettingsScene/SettingsViewController.swift
- Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
- Doolda/Doolda/SettingsScene/SettingsViewCoordinatorProtocol.swift
- Doolda/Doolda/SettingsScene/SettingsViewModel.swift
- Doolda/Doolda/Support/Extensions/UIImage+Extensions.swift
**만만하게 봤던 셋팅뷰가 생각보다 커지고 있어서 pr을 분할해 보내고자 합니다 !!!!**
* 폰트 피커와 스위치는 아직 작업중이라 제외하고 올렸습니다.
* 전체적인 레이아웃 위주로 검토해주시면 감사하겠습니다.
*  설정에 관한 데이터는 DooldaInfoType 이라는 엔티티를 정의해 가져오도록 구현했습니다.
| SettingsView | 오픈 라이센스 화면 | 다크모드 |
| ---- | ---- | ---- |
| ![Simulator Screen Shot - iPhone 13 - 2021-11-22 at 23 23 37](https://user-images.githubusercontent.com/61934702/142879080-87489c69-c457-4f0a-b450-88bfe0c2c4a9.png) | ![Simulator Screen Shot - iPhone 13 - 2021-11-22 at 23 23 40](https://user-images.githubusercontent.com/61934702/142879117-699b7c51-9c48-4a66-85a1-cffd14646245.png) | ![Simulator Screen Shot - iPhone 13 - 2021-11-22 at 23 23 57](https://user-images.githubusercontent.com/61934702/142879146-8b935077-7ab4-4abf-9ca3-ced994410752.png) |
> settings view 일부 구현

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/Application/AppDelegate.swift
- Doolda/Doolda/Data/DataTransferObjects/UserDocument.swift
- Doolda/Doolda/Data/Repositories/FirebaseMessageRepository.swift
- Doolda/Doolda/Data/Repositories/UserRepository.swift
- Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
- Doolda/Doolda/DiaryScene/DiaryViewModel.swift
- Doolda/Doolda/Domain/Entities/PushMessageEntity.swift
- Doolda/Doolda/Domain/Entities/User.swift
- Doolda/Doolda/Domain/Interfaces/FirebaseMessageRepositoryProtocol.swift
- Doolda/Doolda/Domain/UseCases/FirebaseMessageUseCase.swift
- Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/EditPageScene/EditPageViewModel.swift
- Doolda/Doolda/PairingScene/PairingViewCoordinator.swift
- Doolda/Doolda/PairingScene/PairingViewModel.swift
- Doolda/Doolda/Support/Constants/API.swift
* `AppDelegate` 에서 유저정보와 Token을 모두확인해서 매번 새롭게 Set해주고있는데 이전에 이야기했듯 별로 좋지 않은 방식같아 개선이 필요하다.
* Foreground와 Background에 메시지가 들어올때 몇몇 작업들을 해줘야한다. (보통은 새로고침) 아직 미구현된 부분
* Foreground에서 노티가 보여지지않는다. (기본적으로 애플이 제공안함) 그래서 커스텀뷰를 만들어야한다!!
> Firebase 메시지 관련 UseCase, Repository구현 및 실제 동작과 통합

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/Data/DataTransferObjects/PageDocument.swift
- Doolda/Doolda/Data/Interfaces/CoreDataPageEntityPersistenceServiceProtocol.swift
- Doolda/Doolda/Data/Repositories/PageRepository.swift
- Doolda/Doolda/Data/Repositories/RawPageRepository.swift
- Doolda/Doolda/DiaryScene/DiaryViewController.swift
- Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
- Doolda/Doolda/DiaryScene/DiaryViewModel.swift
- Doolda/Doolda/Domain/Entities/PageEntity.swift
- Doolda/Doolda/Domain/Interfaces/RawPageRepositoryProtocol.swift
- Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
- Doolda/Doolda/Domain/UseCases/GetRawPageUseCase.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/Resources/CoreDataModel.xcdatamodeld/CoreDataModel.xcdatamodel/contents
- Doolda/Doolda/Service/CoreData/CoreDataPageEntity+CoreDataProperties.swift
- Doolda/Doolda/Service/CoreData/CoreDataPageEntityPersistenceService.swift
- Doolda/Doolda/Support/Constants/API.swift
* PageEntity의 `timeStamp`를 `createdTime`, `updatedTime`으로 분리했습니다. PageEntity에 관련있는 부분이 수정되어 넓게 변경이 있습니다.
* RawPageEntity를 fetch할때 folder, name이 아니라 RawPageEntity의 MetaData인 PageEntity를 파라미터로 전달하도록 수정했습니다.
* RawPageEntity의 변경을 확인하려면 변경을 비교할 정보가 있어야(로컬에 캐싱된 json 파일이 있는지는 알아야하니까?) 하기 때문에 PageEntity를 CoreData에 유지하기로 결정했습니다. 
* PageEntity를 CoreData에 저장하긴 하지만 11. 23(화) 저녁에 상의 했던것 처럼 PageEntity를 위한 캐시 정책은 제거했습니다.
> PageCaching 정책 수정

- Doolda/Doolda/Data/Interfaces/CoreDataPageEntityPersistenceServiceProtocol.swift
- Doolda/Doolda/Data/Repositories/PageRepository.swift
- Doolda/Doolda/Service/CoreData/CoreDataPageEntityPersistenceService.swift
* 페이지가 새로 생성될 때 무작위로 페이지가 로딩되지 않는 현상을 수정했습니다.
* 페이지 패치시 캐싱과 패치 결과를 동시에 흘리고 있었습니다.
* 캐싱이 완료되기 전에 패치 결과를 사용해 서버에서 데이터를 가져오려고 시도했고 중간에 오류가 생겨서 스트림이 끊겼었습니다.
* rawPageEntity를 가져오는 로직에 캐시 데이터를 참조(최신 데이터인지 확인하는 과정)하는데 이때 캐시에 데이터를 찾지 못해서 오류가 발생했습니다.
* 캐싱이 완료되어야 패치 결과를 스트림에 흘리도록 수정했습니다.
* 수정되기 전 코드를 유지하고, rawPageEntity를 가져오는 로직에 PageEntity의 캐시 데이터가 존재하지 않는다면 디스크에 캐싱된 파일이 없다고 가정하고 새롭게 서버에서 jsonPath를 다운로드 받는 방법도 있습니다.
> 페이지 캐싱 문제 수정

- Doolda/Doolda/Common/CustomActivityIndicator.swift
- Doolda/Doolda/DiaryScene/DiaryBackgroundView.swift
- Doolda/Doolda/DiaryScene/DiaryViewController.swift
- Doolda/Doolda/EditPageScene/EditPageViewController.swift
- Doolda/Doolda/PageDetailScene/PageDetailViewController.swift
- Doolda/Doolda/PairingScene/PairingViewController.swift
- Doolda/Doolda/SettingsScene/SettingsTableViewHeader.swift
- Doolda/Doolda/SettingsScene/SettingsViewController.swift
- Doolda/Doolda/Support/Extensions/UIColor+Extensions.swift
> 일부 색상이 누락된 문제, 네비게이션 바 타이틀이 초기에 설정안되는 문제 해결

- Doolda/Doolda/EditPageScene/StickerPickerScene/PackedStickerCollectionViewCell.swift
* 뷰 크기를 이용해 스티커가 정확히 팩 안으로 들어오도록 origin 조정해서 해결했습니다
> 스티커가 팩에서 튕겨 나가는 현상을 수정

- Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/PageDetailScene/PageDetailViewCoordinator.swift
- Doolda/Doolda/Service/CoreData/CoreDataPageEntityPersistenceService.swift
- Doolda/Doolda/Service/CoreData/CoreDataPersistenceService.swift
* BackgroundContext를 접근시 매번 새로운 인스턴스를 생성하고 있어 앱이 비정상 종료된것으로 보입니다.
* CoreDataPersistenceService를 singleton으로 수정하고 앱 내에서 컨텍스트를 한번만 생성하도록해 이를 방지했습니다.
* 페이지를 CoreData에 저장할 때 수정일이 다른 경우만 저장하도록 했습니다.
> CoreData Context를 계속 생성해 발생하는 오류 수정

- Doolda/Doolda/Data/Repositories/PairRepository.swift
- Doolda/Doolda/Domain/Interfaces/PairRepositoryProtocol.swift
- Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift
- Doolda/Doolda/SettingsScene/SettingsViewController.swift
- Doolda/Doolda/SettingsScene/SettingsViewModel.swift
- Doolda/Doolda/Support/Constants/API.swift
* 혼자 쓰기 유저가 친구 끊기시 친구 연결 화면으로 넘어가지 않는 현상은 친구가 있을때만 화면 전환을 넣어서 이동되지 않고 있던거였습니다.
* 혼자 쓰기 유저도 친구 끊기시 친구 연결 화면으로 전환되도록 수정했습니다.
* 친구 끊기 과정에 Firebase의 Pair Document를 제거하지 않아 다시 혼자 쓰기 사용시 중복된 PairId의 Document를 생성할 수 없어 에러가 발생했습니다.
* 친구 끊기 과정에 Pair Document를 제거해 혼자 쓰기 유저가 계속 혼자 쓰기 모드를 사용해도 에러가 발생하지 않도록 수정했습니다.
> 혼자 쓰기 모드에서 친구 끊기 시 발생하는 오류사항 수정

- Doolda/Doolda/Common/DooldaButton.swift
- Doolda/Doolda/DiaryScene/DiaryCollectionViewHeader.swift
- Doolda/Doolda/DiaryScene/DiaryViewController.swift
- Doolda/Doolda/DiaryScene/FilterOptionScene/FilterOptionBottomSheetViewController.swift
- Doolda/Doolda/EditPageScene/EditPageViewController.swift
- Doolda/Doolda/EditPageScene/TextEditScene/TextEditViewController.swift
- Doolda/Doolda/PageDetailScene/PageDetailViewController.swift
- Doolda/Doolda/PairingScene/PairingViewController.swift
- Doolda/Doolda/SettingsScene/SettingsDetailedInfoViewController.swift
* 다이어리 화면의 상단 버튼, 다이어리 상세 화면의 하단 버튼, 페이지 편집 화면의 상단/하단 버튼 크기를 조금씩 키웠습니다. **크기가 적당한지 꼭!!!! 확인 부탁드립니다!!!**
* 모든 버튼에 햅틱 반응을 추가했고, 햅틱 강도를 light로 통일했습니다.
* 둘다 버튼에 햅틱 반응을 추가했습니다.
* 일부 화면에서 status bar가 살아있길래 쳐 냈습니다 (다이어리 상세화면, 설정 상세화면)
| 수정 전: 다이어리 화면 | 수정 후: 다이어리 화면 |
| :--: | :--: |
| ![IMG_3511](https://user-images.githubusercontent.com/61934702/143845782-b21d52d3-63c7-4c64-b7f7-6c73ccdfafd7.PNG) | ![IMG_3516](https://user-images.githubusercontent.com/61934702/143845880-b17c519e-6fc7-4363-a0c8-76f42f05e024.PNG) | 
| 수정 전: 다이어리 상세 화면 | 수정 후: 다이어리 상세 화면 | 
| :--: | :--: |
| ![IMG_3517](https://user-images.githubusercontent.com/61934702/143846765-f551f535-2c27-4a63-a621-8d374e0156ae.PNG) | ![IMG_3515](https://user-images.githubusercontent.com/61934702/143845963-160db95c-e69f-4af1-a147-06d30b70dbeb …
> 전체적인 버튼 크기 및 햅틱 반응 수정

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/Data/Interfaces/FirebaseNetworkServiceProtocol.swift
- Doolda/Doolda/Data/Repositories/PairRepository.swift
- Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/PairingScene/PairingViewCoordinator.swift
- Doolda/Doolda/Service/Networks/FirebaseNetworkService.swift
- Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
* FirebaseNetworkService에 document를 삭제하는 메소드가 없어서 `deleteDocument()` 를 추가했습니다.
* pairDocument는 필드가 1개 밖에 없어서 따로 DTO를 구현하지 않았는데, 통일성을 위해 구현하는게 좋아 보입니다. 다들 어떻게 생각하시는지요...? 기존에 `PairDocument` 라는 구조체를, DataTransferable 프로토콜을 채택하는 새로운 DTO로 바꾸면 어떨까 싶습니다. urlSessionNetworkService를 사용 안하게 되면 기존 `PairDocument`는 필요 없어질것 같아서요
> PairRepository의 NetworkService 교체 작업

- Doolda/Doolda/Data/Repositories/RawPageRepository.swift
- Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/PageDetailScene/PageDetailViewCoordinator.swift
* `FirebaseNetworkService` 도 다른 Service들과 마찬가지로 싱글턴객체를 만듦.
* 기존 로직이 불필요하게 복잡하게 느껴져서 가독성을 개선하는 과정에서 추가적으로 기존 코드에서부터 있었던 문제를 발견, #523 으로 등록, 개선 예정
`CoreDataPageEntityPersistenceService`, `FileManagerPersistenceService` 같이 동기(맞나?) 인것은 굳이 Combine Publisher를 안쓰는(불필요한 구독을 만들지 않는)쪽으로 가는게 지금의 제 눈에는 더 깔끔해보이는데 다른분들도 동의하시면 작업하면 좋을 것 같습니다.
> RawPageRepository의 NetworkService 교체 작업 

- Doolda/Doolda/Data/Interfaces/FirebaseNetworkServiceProtocol.swift
- Doolda/Doolda/Data/Repositories/PageRepository.swift
- Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
- Doolda/Doolda/Domain/Entities/PageEntity.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/Service/Networks/FirebaseNetworkService.swift
* PageEntity를 DataTransferable 채택하도록 수정했습니다.
* FirebaseNetworkService에 여러 도큐먼드를 요청하기위한 getDocuments를 추가 구현했습니다.
기존 PageRepository에서 PageEntity에 대한 fetch, update 작업 시 PageEntity(MetaData)를 캐싱하도록 구현되어 있습니다. 
Firebase SDK를 활용하게 되면서 Firebase 내부적으로 Offline Data Access를 위해 캐싱 처리를 하는것 같아 보입니다. 
따라서, PageEntity에 대한 추가적인 캐싱이 필요한가 의논해볼 필요가 있는 것 같습니다.
https://firebase.google.com/docs/firestore/manage-data/enable-offline
> PageRepository의 NetworkService 교체 작업

- Doolda/Doolda/Service/CoreData/CoreDataPageEntity+CoreDataProperties.swift
- Doolda/Doolda/Service/CoreData/CoreDataPageEntityPersistenceService.swift
*  `CoreDataPageEntity` 의 `updatedTime` 은 `Optional(Date)` 인데, 이것을 `PageEntity` 의 `Date` 타입과 비교를 시도하니, 매번 `false` 가 반환되는 간단한(?) 문제였음. 알아내는 데 까지는 매우 긴 시간이 걸렸지만....... 코어데이터..어렵네
> RawPageRepository 캐시 hit 문제

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/Common/DooldaTextField.swift
- Doolda/Doolda/SignUpScene/SignUpViewController.swift
| iPhone 11 Pro Max | iPhone SE |
| --- | --- |
| <img width="466" alt="image" src="https://user-images.githubusercontent.com/49086747/168465407-572d701d-f4dc-4523-ae50-ce8651a072ea.png"> | <img width="416" alt="image" src="https://user-images.githubusercontent.com/49086747/168465397-34479534-a241-4254-904a-89a520173f2c.png"> |
* UIResponder를 확장하여 만들어진 keyboardHeightPublisher를 활용하여 scrollview의 contentOffset을 조절 하려고 했으나, textfield간 이동시 keyboardHeight가 0으로 반환되어 정상적으로 처리가 안되는 현상이 발생해 "keyboardWillShowNotification", "keyboardWillHideNotification" 두 노티를 직접 받아 처리하도록 구현했습니다.
* 키보드에서 다음 버튼 터치 시 다음 TextField로 포커스를 옮겨주고 싶은데 TextField가 DooldaTextField로 감싸져 있어 어떻게 처리할지 고민이 드네요 조언좀 부탁드려요
> (#545) SignUpViewController UI 구현

- Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift
- Doolda/Doolda/Data/Repositories/UserRepository.swift
- Doolda/Doolda/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
- Doolda/Doolda/Domain/Interfaces/UseCases/GetMyIdUseCaseProtocol.swift
- Doolda/Doolda/Domain/UseCases/GetMyIdUseCase.swift
- Doolda/Doolda/SplashScene/SplashViewModel.swift
getMyId를 파이어베이스를 통해 가져오게 되면서 이전과 다르게 에러를 포함하게 됐습니다.
따라서 함수의 정의가 아래와 같이 수정되었고 이를 사용하는 SplashViewModel및 AuthenticationViewModel에 error를 처리하는 코드를 추가했습니다.
- before
`func getMyId() -> AnyPublisher<DDID?, Never>`
- after
`func getMyId(for uid: String) -> AnyPublisher<DDID?, Error>`
> uid로 ddid를 가져올 수 있도록 구현

- Doolda/Doolda/SettingsScene/SettingsViewController.swift
- Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
- Doolda/Doolda/SettingsScene/SettingsViewModel.swift
* `SettingsViewModel` 보시면 앱 재시작 시그널을 Notification으로 보내고 있는데, 이것도 combine으로 통일하면 어떨까요?
* 설정 화면에서 폰트 변경시, 하단의 danger zone 버튼 3개의 폰트가 고딕체 같은 이상한 폰트로 변경되는 버그가 있었습니다. 기존에 `SettingsViewController` 에서 `.systemFont(ofSize: 16, weight: .heavy)` 로 폰트를 설정해주고 있었던게 문제였습니다. 도비마요 같은 폰트들은 볼드체가 없기 때문이졍.. 그래서 이 부분 수정해주었숩니다!!
> Feat/#563 로그아웃 기능 구현

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/Data/Interfaces/FirebaseNetworkServiceProtocol.swift
- Doolda/Doolda/Data/Repositories/PageRepository.swift
- Doolda/Doolda/Domain/Interfaces/Repositories/PageRepositoryProtocol.swift
- Doolda/Doolda/Domain/UseCases/UnpairUserUseCase.swift
- Doolda/Doolda/Service/Networks/FirebaseNetworkService.swift
- Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
- Doolda/Doolda/SettingsScene/SettingsViewModel.swift
- Doolda/Doolda/Support/Extensions/StorageReference+Extensions.swift
* Firebase Page Collection에서 Document Id로 prefix 조회하기 위해 아래와 같은 방법을 사용했는데 더 좋은 방법이 있다면 피드백 부탁드려요
```swift
let query = Firestore.firestore().collection(collection.rawValue)
.whereField(fieldPath, isGreaterThanOrEqualTo: prefix)
.whereField(fieldPath, isLessThan: prefix + "z")
```
> 회원탈퇴 및 친구끊기 시 데이터가 삭제 되도록 구현

- Doolda/Doolda/Data/Repositories/UserRepository.swift
- Doolda/Doolda/Domain/Entities/User.swift
- Doolda/Doolda/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
- Doolda/Doolda/Domain/UseCases/UnpairUserUseCase.swift
* `User` 에 대한 조작을 너도 나도 하고있는데 `isAgreed` 프로퍼티가 나중에 추가되었기 때문에 이걸 모두가 알잘딱 커버하지 못한게 문제.. 이런식의 common한 조작은 모두 `User` 내에 정의된 메서드를 이용하도록 했음.
* `resetUser(_:)` 는 사실 필요가 없다. 왜냐면 `User` 를 변형시켜서 `setUser(_:)` 하면 되니까.. 네.. 없앴습니다.
* 위 두개를 적당히 섞어준 결과 데이터 누락(이 경우는 `isAgreed` 정보) 없이 친구 연결해제가 잘 이뤄지게 됐고 덕분에 연결 해제하면 친구연결화면으로 잘 보내집니다!
| 13 mini | 13 Pro |
|:--:|:--:|
| ![13mini](https://user-images.githubusercontent.com/20262392/173846947-affd97c1-a88f-47ba-8d6f-3614e6c5eb43.gif) | ![13pro](https://user-images.githubusercontent.com/20262392/173846974-b56b452f-9870-4c0d-9c87-f2662b1c5f8c.gif) |
> [bug/#580] 친구 연결 해제 문제 해결

- Doolda/Doolda/EditPageScene/StickerPickerScene/StickerPickerBottomSheetViewController.swift
- Doolda/Doolda/EditPageScene/StickerPickerScene/StickerPickerView.swift
#598 버그가 발생한 원인은 UICollectionViewDelegate의 `willDisplay` 에서 드래그 후 화면에 보일 스티커팩을 선택했기 때문입니다.
해당 delegate는 CollectionView에서 다음 보일 셀이 나타나기전에 호출되는데, 이 시점은 드래그가 끝나는 시점을 의미하지 않습니다. 
`func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath)` 
~~이를 해결하기 위해 현재 보이는 셀들 중 첫번째 셀의 index로 currentPack을 선택하게 하도록 했는데 아래 첨부한 gif처럼 왼쪽에서 오른쪽으로 스와이프 할 때, 오른쪽에서 왼쪽으로 스와이프 할 때 page indicator가 이동되는 타이밍이 달라져서 보기에 별로 좋은거 같지 않습니다 🥲~~
~~현재 스티커팩을 선택하기 위해 좋은 방법이 있을까요??~~
드래그가 끝나는 시점에 현재 스티커팩의 index를 결정하도록 수정했습니다.
> (#598) 🚨: 스티커팩 바텀시트의 page indicator가 정상적으로 동작되지 않는 현상 수정

- Doolda/Doolda/DiaryScene/DiaryViewController.swift
- Doolda/Doolda/DiaryScene/DiaryViewModel.swift
다이어리 필터링 시 캐러셀뷰 레이아웃이 올바르게 나타나지 않는 현상을 제거했습니다.
기존 코드에서는 드래그가 끝나는 시점에 `targetContentOffset.pointee` 의 offset을 조절하는 방법으로 캐러셀을 구현했는데
필터링을 할때는 offset을 조절하지 않아 문제가 발생한것으로 파악됩니다.
스크롤을 할때 마지막으로 봤던 페이지의 index를 기록하고,
CollectionView의 DataSource가 변경될 때 스크롤을 조절함으로 이를 해결했습니다.
스크롤을 조절할때 사용한 식은 아래와 같습니다.
`self?.scrollToPage(of: min(self?.viewModel.lastDisplayedPage ?? 0, entities.count))`
다이어리 필터링 중 마지막으로 봤던 페이지의 index가 필터링된 페이지의 개수보다 보다 작아지면 필터링된 페이지 중 마지막 페이지를 보게됩니다.
필터를 적용하지 않고 바텀 시트를 내리게 되면 마지막으로 봤던 페이지가 다시 화면에 나타납니다.
더 좋은 스크롤 방법이 있다면 조언 부탁드려요
| as-is | to-be |
|---|---|
| <img width="300" alt="gif" src="https://user-images.githubusercontent.com/49086747/174848501-4aa4f692-a69c-4ecc-b26f-133ed57f1c52.gif"> | <img width="300" alt="gif" src="https://user-images.githubusercontent.com/49086747/17670245 …
> (#588) 🚨: 다이어리 필터 수정시 다이어리 캐러셀뷰 레이아웃이 올바르게 나타나지 않는 현상 수정

- Doolda/Doolda.xcodeproj/project.pbxproj
- Doolda/Doolda/EditPageScene/EditPageViewController.swift
- Doolda/Doolda/EditPageScene/EditPageViewModel.swift
- Doolda/Doolda/Support/Extensions/UIApplication+Extensions.swift
* `CustomActivityIndicator` 와 같이 모든 뷰를 덮어야 하는 경우는 현재 뷰에 `addSubview(_:)` 하는 대신 `UIWindow.shared.currentWindow` 에 해주면 화면 전체를 가릴 수 있습니다.
| as-is | to-be |
|:-:|:-:|
| <img width="549" alt="스크린샷 2022-06-26 오후 6 24 46" src="https://user-images.githubusercontent.com/20262392/175808038-6ec01763-23f9-4aa0-b6f1-f729e0dc17db.png"> | <img width="472" alt="스크린샷 2022-06-26 오후 6 23 49" src="https://user-images.githubusercontent.com/20262392/175808084-228ddd7e-ca82-477a-9372-1d69edc08cd0.png"> |
> (#600) 🚨: 다이어리 페이지 저장 중 저장/나가기 버튼에 접근이 가능한 문제 수정

- Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/Service/Networks/FirebaseNetworkService.swift
- Doolda/Doolda/Service/Networks/URLSessionNetworkService.swift
| Service에러(시스템관점) | UseCase에러(사용자관점) Service에러(시스템관점) |
|:-:|:-:|
| <img width="350" src="https://user-images.githubusercontent.com/20262392/175811827-1548b83c-fa70-4328-9042-dc2c27289521.gif"> | <img width="350" src="https://user-images.githubusercontent.com/20262392/175811716-158c701d-7dcc-40aa-bf8b-231456e6336e.gif"> |
* 7b15328 이 커밋에서 한 에러(UseCase 에러)가 다른 에러(Repository or Service 에러)를 사유로 표시할 수 있도록 해봤는데, 다른 에러처리에서도 활용하면 매우매우매우매우매우 좋을 것 같습니다. 기존 에러는 사용자 관점 에러만 보여진거라서 약간 불편했습니다.
* 연결성 확인을 매번 해줘야하나 고민했는데 오히려 사용자 경험에 악영향을 끼칠 것 같기도 해서 (어짜피 앱 시작할 때 유저 정보 가져오는 게 제일 크리티컬하지 그 이후로는 뭐 하려해도 어짜피 네트워크때문에 안될테니까) 포기했는데 어떻게 생각하시나요.
> (#601)  TimeOut 에러 추가, 에러에 사유 표시 기능 구현

- Doolda/Doolda/Domain/Interfaces/UseCases/EditPageUseCaseProtocol.swift
- Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
- Doolda/Doolda/EditPageScene/EditPageViewModel.swift
| as-is | to-be |
|:-:|:-:|
| <img width="350" src="https://user-images.githubusercontent.com/20262392/175946434-de1cb8bc-4a72-4a19-89ca-b97398c27412.gif"> | <img width="350" src="https://user-images.githubusercontent.com/20262392/175946245-aef3f505-ee09-4761-9ac6-159dc491c830.gif"> |
* 작성된 페이지를 재편집 할 때에는 가장 아랫단에 깔린 컴포넌부터 위로 올라오며 하나씩 추가(당연하게도 그래야 위에게 아래거 위에 표시되니까)하게되는데, 이 과정에서 `EditPageUseCase` 의 함수를 이용하고 있었습니다. 근데 이 녀석은 컴포넌트를 추가할 때 마다 해당 호출로 추가되는 녀석을 선택된 녀석으로 갱신해주고 있었기 때문에 항상 재편집 시 가장 위에 표시되는 컴포넌트가 선택된 녀석으로 보여지고 있었네요.
> (#589) 🚨: 페이지 재편집시 컴포넌트 선택되지 않도록 변경

- Doolda/Doolda/Data/Interfaces/FirebaseNetworkServiceProtocol.swift
- Doolda/Doolda/Data/Repositories/ImageRepository.swift
- Doolda/Doolda/Data/Repositories/PageRepository.swift
- Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
- Doolda/Doolda/Domain/Interfaces/Repositories/ImageRepositoryProtocol.swift
- Doolda/Doolda/Domain/Interfaces/Repositories/PageRepositoryProtocol.swift
- Doolda/Doolda/Domain/Interfaces/UseCases/ImageUseCaseProtocol.swift
- Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
- Doolda/Doolda/Domain/UseCases/GetRawPageUseCase.swift
- Doolda/Doolda/Domain/UseCases/ImageUseCase.swift
- Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
- Doolda/Doolda/PageDetailScene/PageDetailViewCoordinator.swift
- Doolda/Doolda/Service/Networks/FirebaseNetworkService.swift
* 이슈 원인은 페이지를 저장할 때, page / rawPage / recentlyEditedUser 이 3개를 merge해서 파베에 저장하고 있기 때문이었습니다! 만약 page는 저장됐는데 rawPage 저장에 실패할 경우, 불러올 수 있는 정보가 없어 무한로딩 중인 페이지가 생김.
* 이렇게 3개의 publisher를 merge로 처리하면 #602 이슈 외에도 다른 문제가 발생할 수 있을것 같습니다. 예를들어 recentlyEditedUser만 저장에 실패하면 내가 페이지를 작성했음에도 내 친구에게로 차례가 넘어가지 않는 이슈가 있을거고, page만 저장에 실패할 경우 쓰이지도 않는 rawPage 데이터가 파베에 더미로 남아있을거고 등등..
* 따라서 저장 로직을 merge가 아니라 flatMap으로 변경하였고, rawPage를 fetch 할 때 파베에서 불러올 수 없으면 대응되는 pageEntity 까지 파베에서 같이 제거해주도록 했습니다. 
* 오류가 발생한 rawPage를 제거할 때 image 파일까지 파베에서 찾아 제거해주는게 맞는데, 일단 이 이슈랑 분리해서 작업하는게 나을것 같아 처리하지 않았습니다.
| 스크린샷|
| :--: |
| ![Simulator Screen Recording - iPhone 12 - 2022-07-01 at 19 24 44](https://user-images.githubusercontent.com/61934702/176939762-bdf8c20a-a1cb-444e-8c04-8ae3c158ac9a.gif) |
위와 같이 무한로딩 페이지가 fetch 되면 이를 알아서 …
> Bug/#602 페이지 저장 실패시 무한로딩 페이지 발생 이슈

- Doolda/Doolda/SignUpScene/SignUpViewController.swift
- Doolda/Doolda/SignUpScene/SignUpViewModel.swift
* 비밀번호 조건을 영문, 숫자를 조합하여 최소 8자 이상으로 했습니다. (이게 흔하고 무난한것 같아서) 특문은 자유이지만 ~!@#$%^&* 만 사용 가능합니다.
* 사용가능한 특수문자에 제한이 있는데 이를 어떻게 안내하면 좋을까요? 일단 다음 스크린샷과 같이 문구를 띄우고 있습니다. 여기서 더 길어지면 구구절절일것 같아서 고민되네요....
> (#590) 회원가입 비밀번호 검증 로직 추가
