Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Presentation/Interfaces/SplashViewCoordinatorDelegate.swift
Doolda/Doolda/Presentation/ViewModels/SplashViewModel.swift
Doolda/Doolda/UI/Coordinators/DiaryViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/ParingViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/SplashViewCoordinator.swift
Doolda/Doolda/UI/ViewControllers/SplashViewController.swift

* 아직 ParingViewCoordinator와 DiaryViewCoordinator가 구현되지 않았기 때문에 이 부분은 임시로 파일을 만들어 처리했습니다. (나중에 구현되면 그때 수정하겠습니다)
* 제가 이해한 부분이 우리 팀이 생각하는 coordinator와 잘 맞는지 확인 부탁드립니다. 처음이라 조금 헷갈렸네요 😅

splashViewCoordinator 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/DataTransferObjects/FirebaseDocument.swift
Doolda/Doolda/Data/DataTransferObjects/Pair.swift
Doolda/Doolda/Data/DataTransferObjects/User.swift
Doolda/Doolda/Data/Interfaces/FirebaseNetworkProtocol.swift
Doolda/Doolda/Data/Repositories/UserRepository.swift
Doolda/Doolda/Service/Networks/FirebaseNetworkService.swift
Doolda/FirebaseNetworkTest/FirebaseNetworkTest.swift

* 최대한 Service라는 이름에 맞게 일반화 하도록 작성했습니다.
* 더 좋은 의견이 있으시다면 적극 환영.... 
* 일단 현재 읽기, 쓰기는 firebase에 통신 되는걸 테스트로 확인했습니다.

FirebaseNetworkService 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Presentation/Interfaces/PairingViewCoordinatorDelegate.swift
Doolda/Doolda/Presentation/Interfaces/SplashViewCoordinatorDelegate.swift
Doolda/Doolda/UI/Coordinators/AppCoordinator.swift
Doolda/Doolda/UI/Coordinators/Coordinator.swift
Doolda/Doolda/UI/Coordinators/DiaryViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/ParingViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/SplashViewCoordinator.swift

* `Coordinator` 의 역할과 책임에 대한 고민을 같이 해봐야 할 것 같다. 🤔🤔

Coordinator 에 대한 전반적인 리팩터링 및 PairingViewCoordinator정의

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/Interfaces/UserDefaultsPersistenceServiceProtocol.swift
Doolda/Doolda/Service/Persistences/UserDefaultsPersistenceService.swift
Doolda/FirebaseNetworkTest/FirebaseNetworkTest.swift
Doolda/UserDefaultsPersistenceServiceTest/UserDefaultsPersistenceServiceTest.swift

UserDefaultsPersistentService 설계

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/GetPairIdUseCaseTest.xcscheme
Doolda/Doolda/Domain/Interfaces/UserRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/GeneratePairIdUseCase.swift
Doolda/Doolda/Domain/UseCases/GetPairIdUseCase.swift
Doolda/GeneratePairIdUseCaseTests/GeneratePairIdUseCaseTests.swift
Doolda/GetMyIdUseCaseTest/GetMyIdUseCaseTests.swift
Doolda/GetPairIdUseCaseTest/GetPairIdUseCaseTest.swift

* 테스트부분 처음 해보고있는데 괜찮은지 봐주시면 좋을거같아요. 
* 테스트 커버리지 80.4% !!!

GetPairIdUseCase 및 테스트 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/RefreshPairIdUseCase.swift
Doolda/RefreshPairIdUseCaseTest/RefreshPairIdUseCaseTest.swift

RefreshPairIdUseCase 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/GenerateMyIdUseCase.swift

* 데모를 위해서 테스트를 이후로 미뤄뒀다. (사실 바이패스만 해서 테스트 할게 없기도 하지만...)

GenerateMyIdUseCase 구현

---

Doolda/Doolda/Data/Repositories/UserRepository.swift

firebase에 pair collection을 저장하지 않는 오류 수정

---

Doolda/Doolda/Presentation/ViewModels/PairingViewModel.swift
Doolda/Doolda/UI/Coordinators/ParingViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/SplashViewCoordinator.swift
Doolda/Doolda/UI/ViewControllers/PairingViewController.swift

PairingViewController 통합 및 Coordinator 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/GeneratePairIdUseCase.swift
Doolda/Doolda/Presentation/ViewModels/PairingViewModel.swift
Doolda/Doolda/Presentation/ViewModels/SplashViewModel.swift
Doolda/Doolda/UI/Coordinators/DiaryViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/ParingViewCoordinator.swift
Doolda/Doolda/UI/ViewControllers/DiaryViewController.swift
Doolda/Doolda/UI/ViewControllers/PairingViewController.swift
Doolda/Doolda/UI/ViewControllers/SplashViewController.swift

2주차 데모를 위한 통합

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Service/Networks/FirebaseNetworkService.swift

- 어제 한거랑 똑같이 바꿨는데 어젠 왜 안되고 오늘은 된 걸까요..
- 실 기기로 테스트 해보니 캐싱 안되고 잘 동작합니다 ( 페어링 되어있을 때 인터넷 연결 안되어있으면 연결 안되게 )
https://user-images.githubusercontent.com/64180706/140452206-d6d1fab9-0ee9-4502-8b22-70b6254951aa.MP4

Firebase Firestore cache사용 설정 변경 ( 사용 x )

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/DataTransferObjects/DDIDDataTransferObject.swift
Doolda/Doolda/Domain/Entities/DDID.swift
Doolda/Doolda/Domain/Entities/User.swift

DDID, DDIDDataTransferObject, User Entities 구현

---

Doolda/Doolda/Domain/Entities/DDID.swift
Doolda/Doolda/Domain/Entities/User.swift

DDID, User Equatable 추가 및 id 네이밍 수정

---

Doolda/Doolda/Domain/UseCases/GetMyIdUseCase.swift

GetMyIdUseCase 개선

---

Doolda/Doolda.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Doolda/Doolda/Domain/Entities/DDID.swift
Doolda/Doolda/Presentation/Interfaces/PairingViewCoordinatorDelegate.swift
Doolda/Doolda/Presentation/ViewModels/PairingViewModel.swift
Doolda/Doolda/UI/Coordinators/ParingViewCoordinator.swift
Doolda/Doolda/UI/ViewControllers/PairingViewController.swift

* `friendIdInput` 은 `ViewController` 의 `TextField` 로부터 들어오는 값이라 `PairingVIewModelInput` 에 분류했는데 이 방법이 괜찮은건지, 실제로 잘 동작하는지 모르겠음. 통합하고 함께 살펴봐야할듯.
* 내 `User` 와 친구의 `DDID` 를 이용해 pairing을 해야하는데 `DDID` 는 `DTO` 로 생성하거나 랜덤생성하는 방법밖에 없었음. 그래서 문자열을 주입해 생성하는 생성자를 추가함.
* 이외에도 위 변경사항들로 인해 영향받는 몇몇 코드들의 변경사항이 함께포함됨.

PairingViewModel 개선

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/DataTransferObjects/UserDocument.swift
Doolda/Doolda/Data/Interfaces/URLSessionNetworkServiceProtocol.swift
Doolda/Doolda/Data/Repositories/UserRepository.swift
Doolda/Doolda/Domain/Interfaces/UserRepositoryProtocol.swift
Doolda/Doolda/Service/Networks/URLRequsetBuilder.swift

* 약간의 의문사항이 있지만.. 일단 정해진 프로토콜에 최대한 맞추었습니다

userRepository refactor

---

Doolda/Doolda/Presentation/ViewModels/PairingViewModel.swift

* `DDID` 의 `id` 를 `ddidString` 으로 변경한것에 맞춰 수정

PairingViewModel에서 사용하는 프로퍼티 명 최신화

---

Doolda/Doolda/UI/Coordinators/DiaryViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/ParingViewCoordinator.swift

DiaryViewCoordinator 개선

---

Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift
Doolda/Doolda/Presentation/ViewModels/SplashViewModel.swift
Doolda/Doolda/Service/Networks/URLSessionNetworkService.swift
Doolda/Doolda/UI/Coordinators/DiaryViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/ParingViewCoordinator.swift

* thread 경고가 나길래 dispatch main queue를 사용하는것으로 일단 해결했습니다
*  pairId를 만들어주고 있지 않길래 함수를 추가했습니다

주말 리팩토링 통합

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Presentation/ViewModels/SplashViewModel.swift
Doolda/Doolda/Support/Extensions/UIAlertController+Extensions.swift
Doolda/Doolda/UI/ViewControllers/SplashViewController.swift

* 네트워크 알림창을 앞으로도 계속 사용할 수 있도록 extension으로 구현
* splash view를 적어도 1초동안 보여주도록 수정했습니다

splash view controller 리팩토링 작업

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/DataTransferObjects/PairDocument.swift
Doolda/Doolda/Data/Repositories/PairRepository.swift
Doolda/Doolda/Domain/Interfaces/PairRepositoryProtocol.swift
Doolda/Doolda/Support/Constants/API.swift

* DDID를 내보내는 과정에서 string을 받아서 내보내니까 optional을 한번 풀어줘야하는데 이때 오류를 뭘로 해야할지 모르겠네요.. 일단은 DTOInitError 라고 했습니다만 더 좋은 이름이 있으면 이야기해보면 좋겠습니다!

PairRepository 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/Entities/ComponentEntity.swift
Doolda/Doolda/Domain/Entities/PageEntity.swift
Doolda/Doolda/Domain/Entities/PhotoComponentEntity.swift
Doolda/Doolda/Domain/Entities/PhotoFrameEntity.swift
Doolda/Doolda/Domain/Entities/RawPageEntity.swift
Doolda/Doolda/Domain/Entities/StickerComponentEntity.swift
Doolda/Doolda/Domain/Entities/StickerPackEntity.swift
Doolda/Doolda/Domain/Entities/TextComponentEntity.swift
Doolda/Doolda/Presentation/ViewModels/SplashViewModel.swift

* Component entity를 porotocol로 변경
* entity들을 struct로 구현할지 class로 구현할지 토론 필요..

component entity 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift

EditPageUseCase 프로토콜 정의

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/Interfaces/RawPageRepositoryProtocol.swift

RawPageRepository 프로토콜 정의

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Presentation/ViewModels/EditPageViewModel.swift

EditPageVIewModel의 프로토콜 정의

---

Doolda/Doolda/Support/Constants/API.swift

API의 patchUserDocuement사용시 pairDocument를 사용하는 현상 수정

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/ImageUseCase.swift

(#149) 🤝: ImageUseCase 프로토콜 정의

---

Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift
Doolda/Doolda/UI/Coordinators/ParingViewCoordinator.swift

PairUserUseCase 친구 연결 확인 로직 수정 및 pair 설정 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/Interfaces/FileManagerPersistenceServiceProtocol.swift
Doolda/Doolda/Service/Persistences/FileManagerPersistenceService.swift
Doolda/Doolda/Support/Constants/FileDocuments.swift

* Data 타입만 저장할 수 있도록 간단하게 구현해봤씁니다!

file manager persistence service를 이용해 temp 폴더에 저장하기

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Presentation/ViewModels/PhotoPickerViewModel.swift

* 다같이 프로토콜 검토하는 타이밍에 만들지 못해서 부족한 부분이 있을수 있습니다. 부디 관심을 ^^7

PhotoPickerViewModel 프로토콜 정의

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Doolda/Domain/UseCases/ImageComposeUseCase.swift
Doolda/Doolda/Presentation/ViewModels/SplashViewModel.swift
Doolda/ImageComposeUseCaseTest/ImageComposeUseCaseTest.swift

* 로직이 좀 있어서 테스트를 하려고 했는데 .. 핵심 함수가 다 private이라 좀 고민 중입니다.. 테스트 파일은 일단 무시해주시면 감사하겠습니다

ImageComposeUseCase 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/Entities/ComponentEntity.swift
Doolda/Doolda/Domain/Entities/PhotoComponentEntity.swift
Doolda/Doolda/Domain/Entities/RawPageEntity.swift
Doolda/Doolda/Domain/Entities/StickerComponentEntity.swift
Doolda/Doolda/Domain/Entities/TextComponentEntity.swift
Doolda/Doolda/Domain/Interfaces/PageRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
Doolda/Doolda/Domain/UseCases/ImageUseCase.swift
Doolda/Doolda/Presentation/ViewModels/SplashViewModel.swift
Doolda/Doolda/Support/Extensions/CGColor+Extensions.swift
Doolda/Doolda/Support/Extensions/CGFloat+Extensions.swift
Doolda/Doolda/Support/Extensions/DateFormatter+Extensions.swift
Doolda/EditPageUseCaseTest/EditPageUseCaseTest.swift

* 테스트.. 900줄... 완벽...🧪
* `savePage` 내의 Combine코드는 더 개선해 볼 예정

EditPageUseCase와 테스트, ComponentEntity와 그 하위 클래스 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Doolda/Service/Networks/URLRequsetBuilder.swift
Doolda/Doolda/Service/Networks/URLSessionNetworkService.swift
Doolda/Doolda/Support/Constants/API.swift
Doolda/URLSessionNetworkServiceTest/URLSessionNetworkServiceTest.swift

* createStorageFile로 파이어베이스 스토리지에 data를 추가할 수 있습니다

url session network service에서 firebase storage에 파일 저장하기 기능 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Presentation/ViewModels/PhotoPickerBottomSheetViewModel.swift
Doolda/Doolda/Presentation/ViewModels/PhotoPickerViewModel.swift

PhotoPickerBottomSheetViewModel 구현

---

Doolda/Doolda/Domain/Entities/ComponentEntity.swift
Doolda/Doolda/Domain/Entities/TextComponentEntity.swift
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift

* class도 사랑해줘 애플놈들아...
* 주말에 더 좋은방법을 찾아보는걸루..

ObservableObject를 걷어내고 스스로 변경을 publish해주도록 변경

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/Repositories/RawPageRepository.swift
Doolda/Doolda/Domain/Entities/BackgroundType.swift
Doolda/Doolda/Domain/Entities/ComponentEntity.swift
Doolda/Doolda/Domain/Entities/FontColorType.swift
Doolda/Doolda/Domain/Entities/PhotoComponentEntity.swift
Doolda/Doolda/Domain/Entities/RawPageEntity.swift
Doolda/Doolda/Domain/Entities/StickerComponentEntity.swift
Doolda/Doolda/Domain/Entities/TextComponentEntity.swift
Doolda/Doolda/Domain/Interfaces/RawPageRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift

* PageRepository는 미구현 (API, DTO 모두 구현해야함)

RawPage저장하기 

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/Repositories/PageRepository.swift

* 데모용 임시 PageRepository
* API와 DTO 모두 구현하기에 시간이 부족.

데모용 임시 PageRepository 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/Entities/PhotoFrameType.swift
Doolda/Doolda/Presentation/ViewModels/PhotoPickerBottomSheetViewModel.swift
Doolda/Doolda/Resources/Info.plist
Doolda/Doolda/Support/Extensions/CGImage+Extensions.swift
Doolda/Doolda/UI/ViewControllers/PhotoPickerBottomSheetViewController.swift
Doolda/Doolda/UI/ViewControllers/PhotoPickerViewController.swift
Doolda/Doolda/UI/Views/PhotoPickerCollectionViewCell.swift

PhotoPickerBottomSheetView 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Presentation/Interfaces/EditPageViewCoordinatorProtocol.swift
Doolda/Doolda/Presentation/ViewModels/EditPageViewModel.swift
Doolda/Doolda/UI/Coordinators/EditPageViewCoordinator.swift
Doolda/Doolda/UI/ViewControllers/EditPageViewController.swift
Doolda/Doolda/UI/Views/PageControlView.swift

* 회전및 스케일 조절 후 움직임 시 위치가 튀는 현상
진짜 2시간동안 이유를 찾아봤는데.. 음 회전하면서 origin이 바뀌는데 그게 적용이 안되는 것이 아닐까 추측중 입니다. 근데 그렇다고 계속 origin을 바꿔주면 저 친구가 날라가서.. 방법 찾는 중입니다. 크기가 클 수록 그 튀는 정도가 심해집니다.
* 왼쪽상단일수록 제스쳐 인식이 민감해짐
ㅎㅎ... 이유 찾는 중입니다..

Refactor/edit page UI

---

Doolda/Doolda/Data/Repositories/RawPageRepository.swift
Doolda/Doolda/Domain/Entities/ComponentEntity.swift
Doolda/Doolda/Domain/Entities/PhotoComponentEntity.swift
Doolda/Doolda/Domain/Entities/RawPageEntity.swift
Doolda/Doolda/Domain/Entities/StickerComponentEntity.swift
Doolda/Doolda/Domain/Entities/TextComponentEntity.swift
Doolda/Doolda/Service/Networks/URLSessionNetworkService.swift
Doolda/Doolda/Support/Constants/API.swift
Doolda/Doolda/UI/Coordinators/EditPageViewCoordinator.swift

* 부모 클래스의 배열로 자식 클래스까지 encoding시키는건 쉽다... 그러나 decoding은..? -> 어려웠다.. 너무..ㅋㅋ
* 테스트는 일단 `URLSessionNetworkService` 에 거의 일을 위임하는 쪽에 가까워 고민하다 추가하지 않았는데 여러분들 생각은 어떠신가요? 추가하는편이 나을까요? 만약 추가한다면 `URLSessionNetworkService` 를 이용해야할까요 아니면 그 프로토콜을 따르는 더미를 만들어서 하는게 맞을까요?

RawPageRepository 구현 및 ComponentEntity 인코딩/디코딩 가능하도록 개선

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/Entities/BackgroundType.swift
Doolda/Doolda/UI/ViewControllers/BackgroundTypePickerViewController.swift

BackgroundTypePicker 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Presentation/ViewModels/DiaryViewModel.swift

DiaryViewModel 프로토콜 및 DiaryDisplayMode 정의

---

Doolda/Doolda/Data/Repositories/ImageRepository.swift
Doolda/Doolda/Support/Constants/API.swift
Doolda/Doolda/UI/Coordinators/EditPageViewCoordinator.swift

* 통합하면서 안되는 부분 수정하려했는데 한번에 됏네요 ㅋㅋㅋ
```json
{
"components": [{
"type": "photo",
"frame": [
[199.44134078212289, 749.60422163588385],
[700, 700]
],
"angle": 0,
"aspectRatio": 1,
"imageUrl": "https:\/\/firebasestorage.googleapis.com\/v0\/b\/doolda.appspot.com\/o\/43D2A21E-ECC9-41D5-93FB-DACC56FB115F%2FDA6832AE-FF1D-48F1-910C-467F660A0B65",
"scale": 1
}],
"backgroundType": {
"dooldaBackground": {}
}
}
```

(#211) ♻️: EditPageViewCoordinator 통합

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/GetPageUseCase.swift

GetPageUseCase Protocol 정의

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/CheckTurnUseCase.swift

CheckTurnUseCase Protocol 정의

---

Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift

EditPageUseCase TextComponent에 관한 Protocol 추가 정의

---

Doolda/Doolda/Presentation/Interfaces/DiaryViewCoordinatorProtocol.swift

DiaryViewCoordinator 프로토콜 정의

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Application/SceneDelegate.swift
Doolda/Doolda/Data/Repositories/GlobalFontRepository.swift
Doolda/Doolda/Domain/Interfaces/GlobalFontRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/GlobalFontUseCase.swift
Doolda/Doolda/Presentation/ViewModels/SplashViewModel.swift
Doolda/Doolda/Support/Constants/DoolDaFont.swift
Doolda/Doolda/Support/Extensions/UIFont+Extensions.swift
Doolda/Doolda/Support/Extensions/UserDefaults+Extensions.swift
Doolda/Doolda/UI/Coordinators/SplashViewCoordinator.swift
Doolda/Doolda/UI/ViewControllers/BackgroundTypePickerViewController.swift
Doolda/Doolda/UI/ViewControllers/EditPageViewController.swift
Doolda/Doolda/UI/ViewControllers/PairingViewController.swift
Doolda/Doolda/UI/ViewControllers/PhotoPickerBottomSheetViewController.swift
Doolda/Doolda/UI/ViewControllers/SplashViewController.swift
Doolda/Doolda/UI/Views/CustomActivityIndicator.swift
Doolda/Doolda/UI/Views/PhotoFrameCollectionViewCell.swift
Doolda/Doolda/UI/Views/PhotoPickerCollectionViewCell.swift

* 네이밍 관련해서, 저장하는 것과 반영하는 것을 분리해야해서 set이 보통 반영하는 거라 실제 적용하는 부분에 set을 사용하고 useDefault에 저장하는 부분은 save 를 사용했습니다. 더 좋은 네이밍이 있다면, 추천 부탁드립니다!

Global Font 관련 변경사항 적용

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/Repositories/PushNotificationStateRepository.swift
Doolda/Doolda/Domain/Interfaces/PushNotificationStateRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/PushNotificationStateUseCase.swift
Doolda/Doolda/Support/Extensions/UserDefaults+Extensions.swift

pushNotificationState 관련 Repository와 UseCase 구현

---

Doolda/Doolda/UI/ViewControllers/EditPageViewController.swift

iPhone8+ Page비율 최적화

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Data/Interfaces/CoreDataPageEntityPersistenceServiceProtocol.swift
Doolda/Doolda/Data/Interfaces/CoreDataPersistenceServiceProtocol.swift
Doolda/Doolda/Resources/CoreDataModel.xcdatamodeld/CoreDataModel.xcdatamodel/contents
Doolda/Doolda/Service/CoreData/CoreDataPageEntity+CoreDataClass.swift
Doolda/Doolda/Service/CoreData/CoreDataPageEntity+CoreDataProperties.swift
Doolda/Doolda/Service/CoreData/CoreDataPageEntityPersistenceService.swift
Doolda/Doolda/Service/CoreData/CoreDataPersistenceService.swift

CoreDataPersistenceService 구현

---

Doolda/Doolda/Data/Interfaces/CoreDataPageEntityPersistenceServiceProtocol.swift
Doolda/Doolda/Data/Interfaces/CoreDataPersistenceServiceProtocol.swift
Doolda/Doolda/Data/Repositories/PageRepository.swift
Doolda/Doolda/Service/CoreData/CoreDataPageEntityPersistenceService.swift
Doolda/Doolda/Service/CoreData/CoreDataPersistenceService.swift
Doolda/Doolda/Support/Constants/API.swift

PageRepository의 PageEntity 캐싱 구현

---

Doolda/Doolda/Data/Interfaces/FileManagerPersistenceServiceProtocol.swift
Doolda/Doolda/Data/Repositories/ImageRepository.swift
Doolda/Doolda/Data/Repositories/RawPageRepository.swift
Doolda/Doolda/Domain/Interfaces/ImageRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/ImageUseCase.swift
Doolda/Doolda/Service/Persistences/FileManagerPersistenceService.swift
Doolda/Doolda/Support/Constants/FileDocuments.swift

RawPageRepository 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/DisplayPageUseCase.swift
Doolda/Doolda/Domain/UseCases/GetRawPageUseCase.swift

DisplayPageUseCase 구현

---

Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift

EditPageUseCase 구현

---

Doolda/Doolda/Domain/UseCases/GetPageUseCase.swift

GetPageUseCase 구현

---

Doolda/Doolda/UI/ViewControllers/BackgroundTypePickerViewController.swift

backgroundTypePickerViewCell BorderColor 수정

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/TextUseCase.swift
Doolda/Doolda/Presentation/ViewModels/TextInputViewModel.swift
Doolda/Doolda/UI/Coordinators/DiaryViewCoordinator.swift
Doolda/Doolda/UI/Coordinators/EditPageViewCoordinator.swift
Doolda/Doolda/UI/ViewControllers/EditPageViewController.swift
Doolda/Doolda/UI/ViewControllers/TextInputViewController.swift

text Component page에 추가하는 기능 구현

---

Doolda/Doolda/Domain/Entities/StickerPackEntity.swift
Doolda/Doolda/Domain/UseCases/StickerUseCase.swift
Doolda/Doolda/Presentation/ViewModels/StickerPickerViewModel.swift
Doolda/Doolda/Resources/Assets.xcassets/Color/dooldaStickerPackBody.colorset/Contents.json
Doolda/Doolda/UI/Coordinators/EditPageViewCoordinator.swift
Doolda/Doolda/UI/ViewControllers/EditPageViewController.swift
Doolda/Doolda/UI/ViewControllers/StickerPickerViewController.swift
Doolda/Doolda/UI/Views/PackedStickerCell.swift
Doolda/Doolda/UI/Views/StickerPickerView.swift
Doolda/Doolda/UI/Views/UnpackedStickerCell.swift

*  미개봉 스티커팩은 일단 최대 8개까지만 스티커를 미리 보여주도록 제한해 놨습니다!

미개봉 스티커팩 수정 / 개봉 스티커팩 셀 구현 / stickeEntity 추가하기 구현

---

Doolda/Doolda/UI/ViewControllers/EditPageViewController.swift

페이지 저장중 ActivityIndicator가 나타나도록 구현

---

Doolda/Doolda/UI/ViewControllers/PhotoPickerBottomSheetViewController.swift
Doolda/Doolda/UI/Views/CarouselView.swift

PhotoFramePicker Cell 터치 구현

---

Doolda/Doolda/UI/Views/DiaryPageView.swift

친구가 작성한 페이지에서 스티커가 보이지 않던 현상 수정

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Common/DooldaButton.swift
Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/DiaryScene/DiaryViewModel.swift
Doolda/Doolda/PairingScene/PairingViewController.swift

* 앱 구동시엔 무조건 헤더가 보이도록 변경했어요. 그편이 더 자연스럽기도하구요. (최초로 새로고침을 한번 수행하고 그로인해 애니메이션이 발생함)

Pairing화면 버튼에서 Configuration제거, 앱 구동시 다이어리 페이지가 없으면 offset이 비정상적인 문제 해결

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
Doolda/Doolda/DiaryScene/DiaryViewCoordinatorProtocol.swift
Doolda/Doolda/DiaryScene/DiaryViewModel.swift
Doolda/Doolda/DiaryScene/FilterOptionScene/FilterOptionBottomSheetViewController.swift
Doolda/Doolda/DiaryScene/FilterOptionScene/FilterOptionBottomSheetViewModel.swift

다이어리 페이지 필터링 바텀시트 및 기능 구현

---

Doolda/Tests/EditPageUseCaseTest/EditPageUseCaseTest.swift

* 테스트 할 사항이 더 생긴 것 같은데, 이 부분은 6주차에 더 진행해보는게 좋을 것 같아 일단 테스트가 가능하도록만 개선했어요

EditPageUseCase 테스트 정상화

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/DiaryScene/DiaryCollectionViewCell.swift

* 라벨에는 아예 크기에 따라 폰트를 조절해주는 옵션이 있었네요.. ㅎㅎ 이틀간의 삽질 저 멀리~

다이어리페이지에 나오는 text 잘림현상 수정

---

Doolda/Doolda/DiaryScene/DiaryCollectionViewCell.swift

저장된 페이지를 보여줄때 스티커 비율이 망가지던 현상을 수정했습니다.

저장된 페이지의 스티커 비율 수정

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Application/AppDelegate.swift
Doolda/Doolda/Data/DataTransferObjects/FCMTokenDocument.swift
Doolda/Doolda/Data/Repositories/FCMTokenRepository.swift
Doolda/Doolda/Domain/Interfaces/FCMTokenRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/FCMTokenUseCase.swift
Doolda/Doolda/Doolda.entitlements
Doolda/Doolda/Resources/Info.plist
Doolda/Doolda/Support/Constants/API.swift

* 이제 이놈들을 어떻게 지지고 볶을지가 걱정인데..어렵네요
* `FirebaseMessaging`을 위해 Google info plist가 다시 추가되어야합니다. slack에 공유했으니 그거 프로젝트에 포함시켜주세요

FCM기본 설정, DTO와 API, UseCase 및 Repository 구현

---

Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift

* 혼자 네이게이션이 푸쉬해서 화면 전환이 이상해지던걸 수정했습니다!

photo frame 푸쉬 방식 수정

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/Entities/FontColorType.swift
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
Doolda/Doolda/Domain/UseCases/TextUseCase.swift
Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
Doolda/Doolda/EditPageScene/EditPageViewCoordinatorProtocol.swift
Doolda/Doolda/EditPageScene/EditPageViewModel.swift
Doolda/Doolda/EditPageScene/PageComponentControlView.swift
Doolda/Doolda/EditPageScene/StickerPickerScene/StickerPickerView.swift
Doolda/Doolda/EditPageScene/TextEditScene/FontColorCollectionViewCell.swift
Doolda/Doolda/EditPageScene/TextEditScene/FontColorPickerView.swift
Doolda/Doolda/EditPageScene/TextEditScene/FontSizeControlView.swift
Doolda/Doolda/EditPageScene/TextEditScene/TextEditViewController.swift
Doolda/Doolda/EditPageScene/TextEditScene/TextEditViewModel.swift

* 엥프라멩스... 못지켰는데 너무 커져서 나눠서 올립니다..
* 전체적인 데이터 흐름 : 선택된 텍스트 컴포넌트 -> 그 객체를 textEditViewModel에 전달 -> View단에서 색선택, 크기 조절, 콘텐트 편집 -> 다 끝나면,( 빈 공간을 탭하면 ) 그때 ViewModel에 전달. -> useCase에서 component로 제작 or 편집 -> vm에서 받고 viewController로 넘김 델리게이트로 editpage로 전달
| 색 편집 | 크기 변경 | 있는겨 편집 |
|:----:|:-----:|:----:|
|![색변경](https://user-images.githubusercontent.com/64180706/142982534-8d7280df-7aab-49ee-87dd-00063fc2bb3b.gif) | ![크기변경](https://user-images.githubusercontent.com/64180706/142982614-fd0191cc-0014-49e4-8876-0feb072012dd.gif) | ![ㄹㄹㄹ](https://user-images.githubusercontent.com/64180706/142982666-3d040688-8bcb-45b3-8a26-800be464991e.gif)  |

텍스트 수정, 색변경, 크기 수정 기능 구현

---

Doolda/Doolda/Common/BottomSheetViewController.swift

바텀시트 그림자 수정

---

Doolda/Doolda/DiaryScene/DiaryCollectionViewCell.swift

DiaryViewController에서 fontColor적용 안되는 것 수정

---

Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
Doolda/Doolda/EditPageScene/EditPageViewModel.swift

EditPageUseCaseProtocol의 savePage 수정

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/PageDetailScene/PageDetailViewModel.swift

pageDetailViewModel 프로토콜 작성

---

.gitignore
Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Application/AppDelegate.swift
Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/DiaryScene/DiaryViewModel.swift
Doolda/Doolda/Domain/Entities/PushMessageEntity.swift
Doolda/Doolda/PairingScene/PairingViewController.swift
Doolda/Doolda/PairingScene/PairingViewModel.swift

* 패키지 계속 꼬이는거 너무짜증나요.....제발...좀돼라.. SPM이놈아

Notification 수신시 행위 정의

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/DiaryScene/DiaryCollectionViewCell.swift
Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
Doolda/Doolda/DiaryScene/DiaryViewCoordinatorProtocol.swift
Doolda/Doolda/DiaryScene/DiaryViewModel.swift
Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/PageDetailScene/PageDetailViewController.swift
Doolda/Doolda/PageDetailScene/PageDetailViewModel.swift
Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
Doolda/Doolda/Support/Extensions/UIImage+Extensions.swift

detail view controller과 diary page view에서 데이터 받아오기

---

Doolda/Doolda/Data/Repositories/PageRepository.swift
Doolda/Doolda/Domain/Interfaces/PageRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
Doolda/Doolda/Support/Constants/API.swift
Doolda/Tests/URLSessionNetworkServiceTest/URLSessionNetworkServiceTest.swift

페이지 저장기능을 기존에 작성된 페이지도 저장할 수 있도록 개선

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
Doolda/Doolda/EditPageScene/EditPageViewModel.swift
Doolda/Doolda/PageDetailScene/PageDetailViewController.swift
Doolda/Doolda/PageDetailScene/PageDetailViewCoordinator.swift
Doolda/Doolda/PageDetailScene/PageDetailViewCoordinatorProtocol.swift
Doolda/Doolda/PageDetailScene/PageDetailViewModel.swift

* PageDetailViewModel, PageDetailViewCoordinator 구현을 완료했습니다.
* 편집이 가능하긴한데 새로운 페이지로 작성되는 버그가 있습니다.

페이지 편집 기능 추가

---

Doolda/Doolda/DiaryScene/DiaryCollectionViewHeader.swift
Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/PairingScene/PairingViewController.swift

여기저기에 햅틱피드백 추가하기

---

Doolda/Doolda/EditPageScene/StickerPickerScene/StickerPickerBottomSheetViewController.swift
Doolda/Doolda/EditPageScene/TextEditScene/TextEditViewController.swift

 폰트 색 변경할 때 햅틱 추가

---

Doolda/Doolda/DiaryScene/DiaryCollectionViewCell.swift
Doolda/Doolda/DiaryScene/DiaryCollectionViewHeader.swift
Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/DiaryScene/FilterOptionScene/FilterOptionBottomSheetViewController.swift
Doolda/Doolda/Domain/UseCases/GlobalFontUseCase.swift
Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/EditPageScene/PhotoPickerScene/PhotoPickerBottomSheetViewController.swift
Doolda/Doolda/PageDetailScene/PageDetailViewController.swift
Doolda/Doolda/PairingScene/PairingViewController.swift
Doolda/Doolda/SettingsScene/FontPickerViewController.swift
Doolda/Doolda/SettingsScene/SettingsViewController.swift
Doolda/Doolda/SplashScene/SplashViewController.swift

* 왜인진 모르겠는데 첫 빌드 때 네비게이션 바 폰트가 적용이 안돼요...

글로벌 폰트를 NotiCenter를 쓰도록 개선, 네비게이션바 폰트 문제 해결(일부)

---

Doolda/Doolda/Data/Repositories/PageRepository.swift
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
Doolda/Doolda/EditPageScene/EditPageViewModel.swift
Doolda/Doolda/PageDetailScene/PageDetailViewCoordinator.swift

페이지 편집 오류사항 수정

---

Doolda/Doolda/Common/BottomSheetViewController.swift

바텀시트 그림자 디자인 수정

---

Doolda/Doolda/Common/CustomActivityIndicator.swift
Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/EditPageScene/PhotoPickerScene/PhotoPickerBottomSheetViewController.swift

CustomActivityIndicator 디자인 및 사용성 개선

---

Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/EditPageScene/EditPageViewModel.swift
Doolda/Doolda/SettingsScene/SettingsViewController.swift

편집 화면 디테일 수정

---

Doolda/Doolda/Data/Repositories/UserRepository.swift
Doolda/Doolda/Domain/Interfaces/UserRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift

PairUserUseCase, UserRepository 친구 연결해제 기능 추가

---

Doolda/Doolda/Application/AppDelegate.swift
Doolda/Doolda/SettingsScene/SettingsViewController.swift

앱 실행 중 Notification 수신 여부를 선택할 수 있도록 개선

---

Doolda/Doolda/DiaryScene/DiaryViewModel.swift
Doolda/Doolda/EditPageScene/EditPageViewModel.swift
Doolda/Doolda/PairingScene/PairingViewModel.swift

혼자 사용하는 유저는 노티피케이션을 보이지 않도록 개선

---

Doolda/Doolda/Application/AppCoordinator.swift
Doolda/Doolda/Application/AppDelegate.swift
Doolda/Doolda/Domain/Entities/PushMessageEntity.swift

유저 연결 해제에 대한 노티와 그 행위를 정의

---

Doolda/Doolda/Resources/Assets.xcassets/Color/dooldaWarning.colorset/Contents.json
Doolda/Doolda/SettingsScene/SettingsViewController.swift
Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
Doolda/Doolda/SettingsScene/SettingsViewCoordinatorProtocol.swift
Doolda/Doolda/SettingsScene/SettingsViewModel.swift
Doolda/Doolda/SplashScene/SplashViewCoordinator.swift
Doolda/Doolda/Support/Extensions/UIColor+Extensions.swift

* 친구 끊기 버튼을 추가했습니다.
* alert 창을 띄우도록 했습니다.
* viewModel, useCase, Coordinator를 연결했습니다만 혼자 하기 모드일때 친구 끊기를 하면 다시는 혼자하기를 이용할 수 없는 버그가 있습니다..

친구 끊기 기능 연결

---

Doolda/Doolda/Domain/Entities/StickerPackEntity.swift
Doolda/Doolda/PageDetailScene/PageDetailViewController.swift

* viewWillAppear에서 컴포넌트 subview들을 한번 지워 주는것으로 해결

페이지 편집시, 화면 갱신이 제대로 안되던 버그를 수정

---

README.md

📝: README 업데이트

---

Doolda/Doolda/DiaryScene/DiaryViewModel.swift

* 더 아름다운 방법이 있을 것 같은데 찾아봐도 딱히 뾰족한 수가 안보이네요 (의도: "최소" 1초 딜레이시키기, 현재 : 무조건 + 1초 딜레이시키기)

(#438) ♻️: 새로고침시 네트워크 요청에 1초 딜레이 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift
Doolda/Doolda/Domain/UseCases/UnpairUserUseCase.swift
Doolda/Doolda/SettingsScene/SettingsViewController.swift
Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
Doolda/Doolda/SettingsScene/SettingsViewModel.swift

PairUserUseCase에서 Unpair 로직 분리

---

Doolda/Doolda/EditPageScene/EditPageViewController.swift

페이지 저장중 로딩화면에서 에러 발생에 대한 처리 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Common/DiaryPageView.swift
Doolda/Doolda/DiaryScene/DiaryCollectionViewCell.swift
Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/PageDetailScene/PageDetailViewController.swift

*  `EditPageViewController` ... ㅋㅋㅋㅋ

다이어리 페이지 뷰 리팩터링

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
Doolda/Tests/Dummies/DummyError.swift
Doolda/Tests/Dummies/DummyImageUseCase.swift
Doolda/Tests/Dummies/DummyPageRepository.swift
Doolda/Tests/Dummies/DummyPairRepository.swift
Doolda/Tests/Dummies/DummyRawPageRepository.swift
Doolda/Tests/EditPageUseCaseTest/EditPageUseCaseTest.swift
Doolda/Tests/GetMyIdUseCaseTest/GetMyIdUseCaseTest.swift

🧪: editPageUseCaseTest Dummy 분리

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/GetMyIdUseCaseTest.xcscheme
Doolda/Tests/Dummies/DummyError.swift
Doolda/Tests/Dummies/DummyUserRepository.swift
Doolda/Tests/GetMyIdUseCaseTest/GetMyIdUseCaseTest.swift

GetMyIdUseCase 테스트 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/Dummies/DummyUserRepository.swift
Doolda/Tests/GetUserUseCaseTest/GetUserUseCaseTest.swift

GetUserUseCase 테스트 완료

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/ImageUseCaseTest/ImageUseCaseTest.swift
Doolda/Tests/Dummies/DummyImageRepository.swift

image use case 테스트

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/Dummies/DummyPairRepository.swift
Doolda/Tests/Dummies/DummyUserRepository.swift
Doolda/Tests/PairUserUseCaseTest/PairUserUseCaseTest.swift

PairUserUseCase 테스트 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/Dummies/DummyFCMTokenRepository.swift
Doolda/Tests/FCMTokenUseCaseTest/FCMTokenUseCaseTest.swift

FCMTokenUseCaseTest추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/GlobalFontUseCaseTest.xcscheme
Doolda/Tests/Dummies/DummyGlobalFontRepository.swift
Doolda/Tests/GlobalFontUseCaseTest/GlobalFontUseCaseTest.swift

Global Font UseCase 테스트 완료

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Doolda/Data/Repositories/PushNotificationStateRepository.swift
Doolda/Doolda/Domain/Interfaces/Repositories/PushNotificationStateRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/PushNotificationStateUseCase.swift
Doolda/Tests/Dummies/DummyPushNotificationStateRepository.swift
Doolda/Tests/PushNotificationStateUseCaseTest/PushNotificationStateUseCaseTest.swift

pushNotificationStateUseCase 테스트 완료

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/ImageUseCaseTest.xcscheme
Doolda/Doolda/Domain/Entities/ComponentType.swift
Doolda/Doolda/Domain/Entities/RawPageEntity.swift
Doolda/Tests/TextUseCaseTest/TextUseCaseTest.swift

TextUseCase 테스트 완료

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/RegisterUserUseCaseTest/RegisterUserUseCaseTest.swift

RegisterUserUseCaseTest 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/Dummies/DummyFirebaseMessageRepository.swift
Doolda/Tests/FirebaseMessageUseCaseTest/FirebaseMessageUseCaseTest.swift

FirebaseMessageUseCaseTest 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/CheckMyTurnUseCaseTest/CheckMyTurnUseCaseTest.swift
Doolda/Tests/Dummies/DummyPairRepository.swift

CheckMyTurnUseCase 테스트 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/Dummies/DummyPageRepository.swift
Doolda/Tests/GetPageUseCaseTest/GetPageUseCaseTest.swift

GetPageUseCase 테스트 추가

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/RefreshUserUseCaseTest/RefreshUserUseCaseTest.swift

RefreshUserUseCase 테스트

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda.xcodeproj/xcshareddata/xcschemes/Doolda.xcscheme
Doolda/Tests/CheckMyTurnUseCaseTest/CheckMyTurnUseCaseTest.swift
Doolda/Tests/Dummies/DummyPairRepository.swift
Doolda/Tests/Dummies/DummyRawPageRepository.swift
Doolda/Tests/GetRawPageUseCaseTest/GetRawPageUseCaseTest.swift

RawPageUseCase 테스트 추가

---

Doolda/Doolda/EditPageScene/EditPageViewController.swift
Doolda/Doolda/EditPageScene/TextEditScene/TextEditViewController.swift

text edit view 엥프라멩스 및 edit page view 튕김 오류 수정

---

Doolda/Doolda/EditPageScene/EditPageViewController.swift

♻️: editPageViewController 순환참조 해제

---

Doolda/Doolda/DiaryScene/DiaryViewModel.swift
Doolda/Doolda/DiaryScene/FilterOptionScene/FilterOptionBottomSheetViewModel.swift
Doolda/Doolda/Domain/Interfaces/UseCases/EditPageUseCaseProtocol.swift
Doolda/Doolda/Domain/Interfaces/UseCases/FirebaseMessageUseCaseProtocol.swift
Doolda/Doolda/Domain/Interfaces/UseCases/PairUserUseCaseProtocol.swift
Doolda/Doolda/Domain/Interfaces/UseCases/RefreshUserUseCaseProtocol.swift
Doolda/Doolda/Domain/Interfaces/UseCases/RegisterUserUseCaseProtocol.swift
Doolda/Doolda/Domain/UseCases/EditPageUseCase.swift
Doolda/Doolda/Domain/UseCases/FirebaseMessageUseCase.swift
Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift
Doolda/Doolda/Domain/UseCases/RefreshUserUseCase.swift
Doolda/Doolda/Domain/UseCases/RegisterUserUseCase.swift
Doolda/Doolda/EditPageScene/EditPageViewModel.swift
Doolda/Doolda/EditPageScene/PhotoPickerScene/PhotoPickerBottomSheetViewModel.swift
Doolda/Doolda/PageDetailScene/PageDetailViewModel.swift
Doolda/Doolda/PairingScene/PairingViewModel.swift
Doolda/Doolda/SettingsScene/SettingsViewModel.swift

* Published.Publisher를 AnyPublisher로 수정

Published.Publisher를 AnyPublisher로 수정

---

Doolda/Doolda/SettingsScene/FontPickerViewController.swift

폰트 피커의 높이가 0으로 잡히던 현상 수정

---

Doolda/Doolda/Domain/Interfaces/UseCases/GetMyIdUseCaseProtocol.swift
Doolda/Doolda/Domain/UseCases/GetMyIdUseCase.swift

GetMyIdUseCase에서 uid를 이용하도록 변경

---

Doolda/Doolda/SettingsScene/SettingsViewController.swift
Doolda/Doolda/SettingsScene/SettingsViewModel.swift

피그마랑은 살짝 다르게 버튼을 배치했어요 (그대로하니까 좀 이상해보여서요) 어떤가요?
| 버튼 일렬 | 로그 아웃 | 친구 끊기 | 회원 탈퇴 |
|:---:|:---:|:---:|:---:|
| ![Simulator Screen Shot - iPhone 11 - 2021-12-27 at 20 53 40](https://user-images.githubusercontent.com/20262392/147471814-42415272-4816-484b-ae40-d07612cff5b8.png) | ![Simulator Screen Shot - iPhone 11 - 2021-12-27 at 21 01 01](https://user-images.githubusercontent.com/20262392/147471819-48fcad2b-a7f4-4f7e-bef6-ac73e0ce130f.png)  | ![Simulator Screen Shot - iPhone 11 - 2021-12-27 at 21 01 16](https://user-images.githubusercontent.com/20262392/147471824-cbf55288-f10c-46f8-bb89-eab8b1323613.png) | ![Simulator Screen Shot - iPhone 11 - 2021-12-27 at 21 01 19](https://user-images.githubusercontent.com/20262392/147471825-dc195386-846e-4b0b-8d69-351fd692ea31.png) |

SettingsView 개선

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Domain/Interfaces/UseCases/AuthenticationUseCaseProtocol.swift
Doolda/Doolda/Domain/UseCases/AuthenticationUseCase.swift

AuthenticationUseCase 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AgreementScene/AgreementViewController.swift
Doolda/Doolda/Resources/Assets.xcassets/Color/dooldaTextViewBackground.colorset/Contents.json
Doolda/Doolda/Support/Extensions/UIColor+Extensions.swift

| Light Mode | Dark Mode |
| :--------: | :--------: |
| <img width="333" alt="스크린샷 2021-12-28 15 58 58" src="https://user-images.githubusercontent.com/49086747/147538506-31d18a2c-8538-45c3-a781-ae9c6ec237df.png"> | <img width="333" alt="스크린샷 2021-12-28 15 59 15" src="https://user-images.githubusercontent.com/49086747/147538516-6a9e47fd-c9a2-4d2f-8424-34b78146320d.png"> |

AgreementView 작성

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AgreementScene/AgreementViewModel.swift

AgreementViewModel 작성

---

Doolda/Doolda/Domain/UseCases/GetMyIdUseCase.swift
Doolda/Doolda/SplashScene/SplashViewController.swift
Doolda/Doolda/SplashScene/SplashViewCoordinator.swift
Doolda/Doolda/SplashScene/SplashViewModel.swift

* 확인이안되니 잘되는질 모르겠네요 일단 코드는 깔끔하게 잘 짜진거같아요
* 기존코드 가독성이 너무 떨어지고 불필요한 코드들도 많아서 같이 정리했습니다.

애플로그인에 따른 검증로직 변경 및 리팩터링

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewCoordinator.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift
Doolda/Doolda/Doolda.entitlements

로그인 화면 뜨고 취소 버튼이나 외부 화면을 터치하면 로그인 화면이 이상하게 한번 튀면서 사라지는 현상이 있습니다.. 왜 이런지 원인을 찾는 중입니다.
| 오류 현상 (iPhone 8+, 실기기) |
| :--: |
| ![RPReplay_Final1640681593](https://user-images.githubusercontent.com/61934702/147548192-feed1f18-d599-425d-beba-d0746b77f3c9.gif) |
| 일반 모드 | 다크 모드 |
| :--: | :--: |
| <img width="298" alt="스크린샷 2021-12-28 오후 5 50 47" src="https://user-images.githubusercontent.com/61934702/147547790-9e36cd65-8aad-4145-94c6-463799260f8d.png"> | <img width="298" alt="스크린샷 2021-12-28 오후 5 51 01" src="https://user-images.githubusercontent.com/61934702/147547809-e12d5f5f-a1d7-48eb-87df-5b734c978387.png"> |

AuthenticationViewController, ViewModel 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AgreementScene/AgreementViewController.swift
Doolda/Doolda/AgreementScene/AgreementViewCoordinator.swift

AgreementCoordinator 구현

---

Doolda/Doolda/AgreementScene/AgreementViewController.swift
Doolda/Doolda/AgreementScene/AgreementViewModel.swift

Agreement View, ViewModel, Coordinator 연동

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewCoordinator.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift

AuthenticationCoordinator 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Service/Networks/URLRequsetBuilder.swift
Doolda/Doolda/Service/Networks/URLSessionNetworkService.swift
Doolda/Doolda/Support/Constants/API.swift
Doolda/Doolda/Support/Constants/Secrets.swift

networkService token 인증 과정 추가

---

Doolda/Doolda/Data/Repositories/UserRepository.swift
Doolda/Doolda/Domain/Entities/User.swift
Doolda/Doolda/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
Doolda/Doolda/Domain/Interfaces/UseCases/GetUserUseCaseProtocol.swift
Doolda/Doolda/Domain/UseCases/GetUserUseCase.swift
Doolda/Doolda/Domain/UseCases/PairUserUseCase.swift

* 파베로 바꾸면서 User가 옵셔널로 올 수도 있는 값이 오거나 / 안오고에러나거나 둘중 하나로 바뀐 것 같아서.. 그부분은 DTO 만들어서 옵셔널을 없앴습니다. 혹시 이부분에 문제가 있을 수도 있다면.. 말씀해주세요

UserRepository의 NetworkService 교체 작업 

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/Application/AppDelegate.swift
Doolda/Doolda/Data/Repositories/FCMTokenRepository.swift
Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
Doolda/Doolda/Domain/Entities/FCMToken.swift
Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
Doolda/Doolda/PairingScene/PairingViewCoordinator.swift
Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
Doolda/Doolda/Support/Constants/FirebaseCollection.swift

(#529) ♻️: FCMTokenRepository 가 URLSessionNetworkService를 사용하지않도록 변경

---

Doolda/Doolda/Domain/Interfaces/UseCases/GetMyIdUseCaseProtocol.swift
Doolda/Doolda/Domain/UseCases/GetMyIdUseCase.swift

(#498) ♻️: GetMyIdUseCase에서 uid를 이용하도록 변경

---

Doolda/Doolda/SettingsScene/SettingsViewController.swift
Doolda/Doolda/SettingsScene/SettingsViewModel.swift

SettingsViewController에 로그아웃, 회원탈퇴 버튼 추가

---

Doolda/Doolda/Domain/UseCases/GetMyIdUseCase.swift
Doolda/Doolda/SplashScene/SplashViewController.swift
Doolda/Doolda/SplashScene/SplashViewCoordinator.swift
Doolda/Doolda/SplashScene/SplashViewModel.swift

SplashViewModel 개선

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewCoordinator.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift

Authentication 화면구현 

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AgreementScene/AgreementViewController.swift
Doolda/Doolda/AgreementScene/AgreementViewCoordinator.swift
Doolda/Doolda/AgreementScene/AgreementViewModel.swift
Doolda/Doolda/Common/DooldaCheckBox.swift
Doolda/Doolda/Resources/Assets.xcassets/Color/dooldaTextViewBackground.colorset/Contents.json
Doolda/Doolda/SplashScene/SplashViewModel.swift
Doolda/Doolda/Support/Extensions/UIColor+Extensions.swift

* 서비스 이용 약관 및 개인정보 이용 동의를 커스텀 체크박스(DooldaCheckBox)를 통해 입력받도록 UI를 구성해 봤습니다.
체크박스 UI 가 앱과 어울리는지 한번 봐주세요
<br/>
| LightMode | DarkMode | 
| :--------: | :--------: |
| <img width="750" alt="" src="https://user-images.githubusercontent.com/49086747/160133031-d9a53a51-d05a-460e-9189-d550cd5c34a0.png"> |  <img width="750" alt="" src="https://user-images.githubusercontent.com/49086747/160133060-07a869d9-5247-4b7c-92cd-cb7e1ad12b30.png"> |
| <img width="750" alt="" src="https://user-images.githubusercontent.com/49086747/161366121-9a878b40-de93-47e7-9733-5acac2849dab.png"> | <img width="750" alt="" src="https://user-images.githubusercontent.com/49086747/161366119-8107ab20-95b5-4e20-a93c-7a949bbe36cc.png"> |
<br/>

AgreementView 구현

---

Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift

* nonce 비교시  raw nonce가 아닌 암호화된 nonce를 넣어주고있엇음.
* 추가적으로 ViewController에 있던 몇몇 로직을 ViewModel로 분리시킴 (베스트는 UseCase까지 만드는거 같긴 한데..)
* 삐그덕거리는 부분이 많은 것 같음. 함께 봅시다

애플로그인 불가 문제 해결

---

Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewCoordinator.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift
Doolda/Doolda/DiaryScene/DiaryViewCoordinator.swift
Doolda/Doolda/DiaryScene/DiaryViewModel.swift
Doolda/Doolda/Domain/UseCases/GetMyIdUseCase.swift
Doolda/Doolda/EditPageScene/EditPageViewCoordinator.swift
Doolda/Doolda/EditPageScene/EditPageViewModel.swift
Doolda/Doolda/PairingScene/PairingViewCoordinator.swift
Doolda/Doolda/PairingScene/PairingViewModel.swift
Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
Doolda/Doolda/SettingsScene/SettingsViewModel.swift
Doolda/Doolda/SplashScene/SplashViewCoordinator.swift
Doolda/Doolda/SplashScene/SplashViewModel.swift

* 뭔가 전반적인 로그인 스텝을 한번 정리해야 할 것 같습니다
* 어디서 uid를 사용하고 어디서 부터 uuid/ddid를 사용하는 지 확실하게 해야할 것 같아요... :)
* 승훈님의 로그인 문제 해결에서 (서버에 들어가는 것 확인 ) 로그인 되었을 시 -> 약관동의페이지로 이동 까지 구현되어 있습니다

coordinator 개선

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewCoordinator.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift
Doolda/Doolda/Common/DooldaTextField.swift
Doolda/Doolda/Domain/Interfaces/UseCases/SignUpUseCaseProtocol.swift
Doolda/Doolda/Domain/UseCases/SignUpUseCase.swift
Doolda/Doolda/SignUpScene/SignUpViewController.swift
Doolda/Doolda/SignUpScene/SignUpViewCoordinator.swift
Doolda/Doolda/SignUpScene/SignUpViewModel.swift
Doolda/Doolda/SplashScene/SplashViewCoordinator.swift
Doolda/Doolda/SplashScene/SplashViewModel.swift

coordinator 개선 및  SignUp Sence 관련 객체 구현

---

Doolda/Doolda.xcodeproj/project.pbxproj
Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift
Doolda/Doolda/Common/DooldaTextField.swift
Doolda/Doolda/Domain/Interfaces/UseCases/AuthenticationUseCaseProtocol.swift
Doolda/Doolda/Domain/UseCases/AuthenticationUseCase.swift

* 메일, 비밀번호 입력이 안되어있으면 로그인 버튼을 비활성화 하도록 했습니다.
* DooldaTextfield에 returnPublisher와 responder 관련된 메소드를 추가했습니다.
* 로그인 에러 발생시 alert를 띄우도록 했습니다.

Authentication View 및 ViewModel 작업

---

Doolda/Doolda/AuthenticationScene/AuthenticationViewCoordinator.swift
Doolda/Doolda/SignUpScene/SignUpViewController.swift
Doolda/Doolda/SignUpScene/SignUpViewCoordinator.swift
Doolda/Doolda/SignUpScene/SignUpViewModel.swift
Doolda/Doolda/SplashScene/SplashViewCoordinator.swift

* authentication coordinator에서 다른 페이지 이동 연결 완료
* signup page에서 signin으로 돌아가는 기능 구현 완료

Feat/#555 새로운 view controller들 화면 연결

---

Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/Common/DooldaTextField.swift

* AuthenticationView에서 화면 터치시 키보드 내리기를 추가했습니다
* discardableResult를 추가했습니다

DooldaTextField 수정사항

---

Doolda/Doolda/AuthenticationScene/AuthenticationViewCoordinator.swift
Doolda/Doolda/Data/Repositories/UserRepository.swift
Doolda/Doolda/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
Doolda/Doolda/Domain/UseCases/CreateUserUseCase.swift
Doolda/Doolda/Support/Constants/FirebaseCollection.swift

* `CreateUserUseCase.create(uid: String)` 의 동작이 제가 생각한 로직이 맞는지 한번 확인 부탁드립니다~~
- DDID를 새로 생성한 후, uid와 매핑되는 컬렉션(ddidDictionary)에 저장
- 저장 후, 해당 DDID를 id로 갖는 User를 생성하여 컬렉션(user)에 저장
* uid -> DDID 로 매핑되는 파베 컬렉션을 일단 임시로 ddidDictionary 라는 이름을 붙였는데, 별로 마음에 들지 않네요.. 더 좋은 이름 추천받습니다!
* 파베에 ddidDictionary와 user 컬렉션이 생성되는 것 까지는 확인 했습니다~~

CreateUserUseCase 구현 및 UserRepository 수정

---

Doolda/Doolda/Application/AppDelegate.swift
Doolda/Doolda/Data/Repositories/UserRepository.swift
Doolda/Doolda/Domain/Interfaces/Repositories/UserRepositoryProtocol.swift
Doolda/Doolda/Domain/Interfaces/UseCases/GetMyIdUseCaseProtocol.swift
Doolda/Doolda/Domain/Interfaces/UseCases/SignUpUseCaseProtocol.swift
Doolda/Doolda/Domain/UseCases/GetMyIdUseCase.swift
Doolda/Doolda/Domain/UseCases/SignUpUseCase.swift
Doolda/Doolda/SignUpScene/SignUpViewModel.swift

deprecated된 코드 제거 및 Closure를 Combine으로 교체

---

Doolda/Doolda/AuthenticationScene/AuthenticationViewController.swift
Doolda/Doolda/AuthenticationScene/AuthenticationViewModel.swift
Doolda/Doolda/Domain/UseCases/AppleAuthProvideUseCase.swift
Doolda/Doolda/PairingScene/PairingViewCoordinator.swift
Doolda/Doolda/SettingsScene/SettingsViewCoordinator.swift
Doolda/Doolda/SettingsScene/SettingsViewModel.swift
Doolda/Doolda/SignUpScene/SignUpViewController.swift
Doolda/Doolda/SignUpScene/SignUpViewModel.swift
Doolda/Doolda/SplashScene/SplashViewController.swift
Doolda/Doolda/SplashScene/SplashViewCoordinator.swift
Doolda/Doolda/SplashScene/SplashViewModel.swift
Doolda/Doolda/Support/Extensions/UIAlertController+Extensions.swift

회원가입 뷰 개선 및 회원가입 시 에러처리 

---

Doolda/Doolda/AgreementScene/AgreementViewController.swift
Doolda/Doolda/SignUpScene/SignUpViewController.swift
Doolda/Doolda/SignUpScene/SignUpViewCoordinator.swift
Doolda/Doolda/SignUpScene/SignUpViewModel.swift
Doolda/Doolda/SplashScene/SplashViewController.swift

회원가입 UI 및 로직 개선

---

Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/SettingsScene/SettingsTableViewCell.swift
Doolda/Doolda/SettingsScene/SettingsTableViewHeader.swift
Doolda/Doolda/SettingsScene/SettingsViewController.swift

* 설정화면 danger zone UI를 변경했는데 디자인적인 부분이라 괜찮은지 피드백 한번 부탁드림미다

Feat/#571, #572 설정화면 수정 및 네비게이션바 이슈 해결

---

Doolda/Doolda/EditPageScene/BackgroundTypePickerScene/BackgroundTypePickerViewController.swift

(#596) 🚨: 배경선택 시트의 Vertical Scroll Indicator 안보이게 수정

---

Doolda/Doolda/EditPageScene/PhotoPickerScene/CarouselView.swift

사진추가 바텀시트의 PageControl이 올바르게 동작하지 않는 현상 수정

---

Doolda/Doolda/DiaryScene/DiaryViewController.swift
Doolda/Doolda/DiaryScene/DiaryViewModel.swift
Doolda/Doolda/Support/Extensions/UIAlertController+Extensions.swift

(#619) 🚨: DiaryViewController에 error 처리 기능 추가

---

Doolda/Doolda/EditPageScene/TextEditScene/TextEditViewController.swift

(#594) 🚨: slider value가 0으로 들어올 때 TextView를 변경하지 않도록 수정

---

Doolda/Doolda/EditPageScene/TextEditScene/TextEditViewController.swift

(#593) 🚨: 디폴트 textView Color를 black으로 지정
